// Generated by Haxe 4.2.2
(function ($global) { "use strict";
class Main {
	constructor() {
		console.log("src/Main.hx:13:","Main");
		Neutralino.init();
		window.document.getElementById("info").innerHTML = window.NL_TEST;
		Neutralino.computer.getRamUsage().then(function(res) {
			console.log("src/Main.hx:23:","Your ram size: " + res.ram.total / 1000000 + "GB");
			console.log("src/Main.hx:24:","x");
		});
		this.setupKey();
		Neutralino.events.on("windowClose",$bind(this,this.onWindowClose));
	}
	onWindowClose() {
		Neutralino.app.exit();
	}
	setupKey() {
		window.onkeydown = $bind(this,this.onKeyDown);
	}
	onKeyDown(e) {
		window.document.getElementById("key").innerHTML = "ctrl: " + (e.ctrlKey == null ? "null" : "" + e.ctrlKey) + " meta: " + (e.metaKey == null ? "null" : "" + e.metaKey);
		if(e.metaKey == true) {
			if(e.key == "q") {
				Neutralino.app.exit();
			}
		}
	}
	foo() {
		console.log("src/Main.hx:106:","foo");
		window.document.getElementById("name").innerHTML = "foo";
	}
	static main() {
		new Main();
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
class hxasync_NoReturn {
	static _new(value) {
		return null;
	}
}
class hxasync_AsyncMacroUtils {
}
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
{
}
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
